name: "Bug report"
description: "Report an issue or unexpected behavior in Snap Swipe."
title: "[Bug]: "
labels: ["bug"]
body:
  - type: input
    id: summary
    attributes:
      label: Summary
      description: Briefly describe the issue.
      placeholder: e.g., Swipe left advances but does not delete the photo
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Include a clear sequence so we can reproduce.
      placeholder: |
        1. Open Snap Swipe
        2. ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: What you thought would happen.
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      placeholder: What actually happened (include errors shown, if any).
    validations:
      required: true
  - type: input
    id: device
    attributes:
      label: Device details
      description: Model and Android version.
      placeholder: e.g., Pixel 7, Android 14
    validations:
      required: true
  - type: textarea
    id: media
    attributes:
      label: Screenshots or logs (optional)
      description: Drag-and-drop screenshots, screen recordings, or relevant logs.
    validations:
      required: false
